# Run from the Brelly project root: .\pipeline\check_system.ps1
"PYTHON312=$(py -3.12 --version 2>&1 | Out-Null; if ($LASTEXITCODE -eq 0) { 'ok' } else { 'missing' })"
"GDAL_PY=$(py -3.12 -c 'from osgeo import gdal' 2>&1 | Out-Null; if ($LASTEXITCODE -eq 0) { 'ok' } else { 'missing' })"
"VENV=$(if (Test-Path .venv\Scripts\python.exe) { 'ok' } else { 'missing' })"
"DEPS=$(.venv\Scripts\python.exe -c 'from osgeo import gdal; import pyproj, shapely, numpy' 2>&1 | Out-Null; if ($LASTEXITCODE -eq 0) { 'ok' } else { 'missing' })"
"BLENDER=$(if (Get-Command blender -EA 0) { 'ok' } else { 'missing' })"
"GLTFPACK=$(if (Get-Command gltfpack -EA 0) { 'ok' } else { 'missing' })"
"DATA_DEM=$(if (Test-Path data\alti3d.tif) { 'ok' } else { 'missing' })"
"DATA_TLM=$(if (Test-Path data\swissTLM3D.gpkg) { 'ok' } else { 'missing' })"
"CONFIG=$(if (Get-ChildItem pipeline\config\*.json -Exclude example.json -EA 0) { 'ok' } else { 'missing' })"
